name       : gavl
version    : 1.4.0
release    : 1
source     :
    - https://ufpr.dl.sourceforge.net/project/gmerlin/gavl/1.4.0/gavl-1.4.0.tar.gz : 51aaac41391a915bd9bad07710957424b046410a276e7deaff24a870929d33ce
license    : GPL-3.0
component  : multimedia.video
summary    : A library for handling uncompressed audio and video data.
description: |
    Gavl defines generic types for audio and video formats,
    which are applicable to a wide range of multimedia applications.
    In addition, it provides conversion functions from all possible formats
    to all other formats.
    If you want to write a multimedia application, gavl will help you a lot:
    You do not have to mess around with the large varieties of pixelformats,
    interleaving modes, audio sample formats and so on.
builddeps  :
    - doxygen
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
